require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'RepOnePersonal' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Charts, as it doesn't seem to work normally
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  # Firebase Pods
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Analytics', '~> 6.3.0'
  pod 'Firebase/RemoteConfig', '~> 6.3.0'

  # Somehow these are automatically installed already, unlike the above ones, I don't know why
  # pod 'Firebase/Crash', '~> 6.3.0' # not sure if still needed, does it fight crashlytics or fabric or work with it? also can't find it when i run it
  # pod 'Fabric', '1.9.0' # used to be 1.7.2, not sure if still needed
  # pod 'Crashlytics', '3.14.0' # used to be 3.9.3, not sure if still needed

  pod 'GoogleIDFASupport' # for firebase analytics audience

  # Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  target 'RepOnePersonalTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
