export const EMPTY_METRIC = 'EMPTY_METRIC';
export const AVG_VELOCITY_METRIC = 'AVG_VELOCITY_METRIC';
export const RPE_METRIC = 'RPE_METRIC';
export const DURATION_METRIC = 'DURATION_METRIC';
export const ROM_METRIC = 'ROM_METRIC';
export const PKH_METRIC = 'PKH_METRIC';
export const PKV_METRIC = 'PKV_METRIC';
export const FORCE_METRIC = 'FORCE_METRIC';
export const FORCE_HEIGHT_METRIC = 'FORCE_HEIGHT_METRIC';
export const POWER_METRIC = 'POWER_METRIC';
export const POWER_HEIGHT_METRIC = 'POWER_HEIGHT_METRIC';
export const LINEAR_3D_AVG_VELOCITY_METRIC = 'LINEAR_3D_AVG_VELOCITY_METRIC';
export const LINEAR_3D_ROM_METRIC = 'LINEAR_3D_ROM_METRIC';
export const WORK_METRIC = 'WORK_METRIC';
export const WORK_LOCATION_METRIC = 'WORK_LOCATION_METRIC';
export const FORCE_LOCATION_METRIC = 'FORCE_LOCATION_METRIC';
export const POWER_LOCATION_METRIC = 'POWER_LOCATION_METRIC';

export const EMPTY_QUANTIFIER = 'EMPTY_QUANTIFIER';
export const FIRST_REP_QUANTIFIER = 'FIRST_REP_QUANTIFIER';
export const LAST_REP_QUANTIFIER = 'LAST_REP_QUANTIFIER';
export const MIN_QUANTIFIER = 'MIN_QUANTIFIER';
export const MAX_QUANTIFIER = 'MAX_QUANTIFIER';
export const AVG_QUANTIFIER = 'AVG_QUANTIFIER';
export const ABS_LOSS_QUANTIFIER = 'ABS_LOSS_QUANTIFIER';
export const PERCENT_LOSS_QUANTIFIER = 'PERCENT_LOSS_QUANTIFIER';
export const MAX_EVER_QUANTIFIER = 'MAX_EVER_QUANTIFIER';
export const MIN_EVER_QUANTIFIER = 'MIN_EVER_QUANTIFIER';
export const SET_LOSS_QUANTIFIER = 'SET_LOSS_QUANTIFIER';
export const PEAK_END_QUANTIFIER = 'PEAK_END_QUANTIFIER';

// PHASE

export const CONCENTRIC = 'CONCENTRIC';
export const ECCENTRIC = 'ECCENTRIC';
