export const DEVICE_BLUETOOTH_OFF = 'DEVICE_BLUETOOTH_OFF';
export const CONNECTING = 'CONNECTING';
export const CONNECTED = 'CONNECTED';
export const DISCONNECTED = 'DISCONNECTED';
export const DISCONNECTING = 'DISCONNECTING';
export const RECONNECTING = 'RECONNECTING';
